// responseMessage.js
module.exports = {
    NULL_VALUE: "필요한 값이 없습니다.",
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_FAIL: "회원 가입 실패",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "로그인 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_USER: "존재하지 않는 유저 id 입니다.",
    DUPLICATE_USER: "존재하지 않는 유저 id 입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    PRODUCT_CREATE_SUCCESS: "상품 추가 성공",
    PRODUCT_CREATE_FAIL: "상품 추가 실패",
    PRODUCT_UPDATE_SUCCESS: "상품 수정 성공",
    PRODUCT_UPDATE_FAIL: "상품 수정 실패",
    PRODUCT_READ_ALL_SUCCESS: "상품 전체 조회 성공",
    PRODUCT_READ_ALL_FAIL: "상품 전체 조회 실패",
    PRODUCT_READ_BASKET_SUCCESS: "장바구니 조회 성공",
    PRODUCT_READ_BASKET_FAIL: "장바구니 조회 실패",
    PRODUCT_ADD_BASKET_SUCCESS: "장바구니 추가 성공",
    PRODUCT_ADD_BASKET_FAIL: "장바구니 추가 실패",
    PRODUCT_ADD_BASKET_FAIL_DUPLICATE: "장바구니 추가 실패 - 이미 장바구니에 추가하였습니다",
    PRODUCT_DELETE_BASKET_SUCCESS: "장바구니 삭제 성공",
    PRODUCT_DELETE_BASKET_FAIL: "장바구니 삭제 실패",
    PRODUCT_READ_STORAGE_SUCCESS: "보관함 조회 성공",
    PRODUCT_READ_STORAGE_FAIL: "보관함 조회 실패",
    PRODUCT_ADD_STORAGE_SUCCESS: "보관함 추가 성공",
    PRODUCT_ADD_STORAGE_FAIL: "보관함 추가 실패",
    PRODUCT_USE_STORAGE_SUCCESS: "보관함 사용 성공",
    PRODUCT_USE_STORAGE_FAIL: "보관함 사용 실패",
    PRODUCT_USE_STORAGE_FAIL_ALREADY_USE: "보관함 사용 실패 - 이미 사용한 보관함입니다",
    PRODUCT_READ_OFTEN_SUCCESS: "자주 보는 상품 조회 성공",
    PRODUCT_READ_OFTEN_FAIL: "자주 보는 상품 조회 실패",
    PRODUCT_READ_RECENT_SUCCESS: "최근 본 상품 조회 성공",
    PRODUCT_READ_RECENT_FAIL: "최근 본 상품 조회 실패",
    PRODUCT_READ_SUCCESS: "상품 조회 성공",
    PRODUCT_READ_FAIL: "상품 조회 실패",
    PRODUCT_UPDATE_SUCCESS: "상품 수정 성공",
    PRODUCT_UPDATE_FAIL: "상품 수정 실패",
    PRODUCT_DELETE_SUCCESS: "상품 삭제 성공",
    PRODUCT_DELETE_FAIL: "상품 삭제 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_USER: "존재하지 않는 유저 입니다.",
    NO_PRODUCT: "존재하지 않는 상품 입니다.",
    NO_STORAGE: "존재하지 않는 보관 입니다.",
    NO_BASKET: "존재하지 않는 장바구니 입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    INTERNAL_SERVER_ERROR: "서버 내부 오류",
    EXPIRED_TOKEN: "만료된 토큰",
    INVALID_TOKEN: "잘못된 토큰값",
    VALID_TOKEN: "유효한 토큰",
    REFRESH_TOKEN: "리프레시 토큰",
}